name: Build and Deploy

on:
  push:
    branches:
      - blog

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Login to Gitea Registry
        run: echo "Muzriuzt8" | docker login gitea.nas.com -u ctrdh --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t gitea.nas.com/ctrdh/blog:latest -t gitea.nas.com/ctrdh/blog:${{ github.sha }} .
          docker push gitea.nas.com/ctrdh/blog:latest
          docker push gitea.nas.com/ctrdh/blog:${{ github.sha }}
