name: Build and Push

on:
  push:
    branches:
      - blog

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push image
        run: |
          docker build \
            -t localhost:30500/blog:${{ github.sha }} \
            -t localhost:30500/blog:latest \
            .
          docker push localhost:30500/blog:${{ github.sha }}
          docker push localhost:30500/blog:latest
